Peter/header
lagcloud/lagcloud_website pull request #16
Opened 2023-10-05 13:59 UTC by PeterFreemann

header and logo components

2023-10-05 14:35 UTC, kobomarun requested changes
Kindly made changes based on the comments made

2023-10-05 14:35 UTC, kobomarun commented on lagcloud-website/src/Test.jsx
> +function Test() {
delete this file

2023-10-05 14:35 UTC, kobomarun commented on lagcloud-website/src/index.js
> +import reportWebVitals from './reportWebVitals';
remove this liine

2023-10-05 14:35 UTC, kobomarun commented on lagcloud-website/src/index.js
> +reportWebVitals();
remove this line

2023-10-05 14:35 UTC, kobomarun commented on lagcloud-website/src/Components/Logo.js
> +        <a className='navbar-brand' href='#'><img src='static/images/lagcloud-removebg-preview.png' alt='logo'/></a>
make this line look like the code below
<a className='navbar-brand' href='#'>
    <img src='static/images/lagcloud-removebg-preview.png' alt='logo'/>
</a>

2023-10-05 14:35 UTC, kobomarun commented on lagcloud-website/src/App.css
> +.App {
remove this file

2023-10-05 14:41 UTC, PeterFreemann commented on lagcloud-website/src/Test.jsx
> +function Test() {
done @kobomarun

2023-10-13 11:16 UTC, fodeyemi commented on lagcloud-website/src/App.js
If this is a React component it should be a `.jsx` file, not `.js`

2023-10-13 11:16 UTC, fodeyemi commented on lagcloud-website/src/App.test.js
React component should be in .jsx files please, discussed with @PeterFreemann

2023-10-26 19:41 UTC, merged