contactus updates
lagcloud/lagcloud_website pull request #26
Opened 2023-12-10 20:45 UTC by PeterFreemann

contact us page

2023-12-11 12:06 UTC, kobomarun requested changes
in firebase.json file

remove what is there and add rhe following code:
{
  "hosting": {
    "public": "public/build",
    "ignore": [
      "firebase.json",
      "**/.*",
      "**/node_modules/**"
    ],
    "rewrites": [
      {
        "source": "**",
        "destination": "/index.html"
      }
    ]
  }
}

Save and push

2023-12-13 13:21 UTC, kobomarun requested changes
Make sure you check the responsiveness too

2023-12-13 13:21 UTC, kobomarun commented on lagcloud-website/src/component/Footer.jsx
> +          <Link>Help & Support</Link> | <Link>Privacy Policy</Link> | <Link>Terms & Conditions</Link>
this will throw a console error.
Link should be like this
<Link to="#">

2023-12-13 13:21 UTC, kobomarun commented on lagcloud-website/public/assets/css/main.css
> +  padding: 0 140px;
did you test this on mobile?

2023-12-20 11:44 UTC, kobomarun commented on lagcloud-website/src/component/Contactus.jsx
> +                      <input type="email" className="form-control" id="Number" name="Number" required/>
This should be `type=number `

2023-12-20 11:47 UTC, kobomarun reviewed
Make the changes

2023-12-20 11:47 UTC, kobomarun commented on lagcloud-website/src/component/Contactus.jsx
> +                      <input type="email" className="form-control" id="Company" name="Company" required/>
This should be `type=text `

2023-12-20 11:47 UTC, kobomarun commented on lagcloud-website/src/component/Contactus.jsx
> +      <form className='mt-4' action="your-server-action " method="POST">
remove this  <form className='mt-4' action="your-server-action " method="POST">
replace it with
<form className='mt-4' action="https://hooks.zapier.com/hooks/catch/17334671/3a8x32g/ " method="POST" target="_blank">

2023-12-20 11:50 UTC, kobomarun requested changes

2023-12-20 11:50 UTC, kobomarun commented on lagcloud-website/src/component/Contactus.jsx
> +                      <label for="email" className="form-label">Number</label>
This should be Phone Number not Number

2023-12-20 12:01 UTC, kobomarun requested changes
Please. Do Validation for the forms especially email

2023-12-22 12:07 UTC, kobomarun requested changes

2023-12-22 12:07 UTC, kobomarun commented on lagcloud-website/src/component/Contactus.jsx
> +      <form className='mt-4' action="your-server-action " method="POST">
I still await your review on this

2023-12-22 16:31 UTC, kobomarun requested changes
you didnt replace the <form i asked you to do

2023-12-22 16:32 UTC, kobomarun commented on lagcloud-website/src/component/Contactus.jsx
> +      <form className='mt-4' action="your-server-action " method="POST">
You did not attend to this one

2024-01-03 14:13 UTC, PeterFreemann commented on lagcloud-website/public/assets/css/main.css
> +/*.hero-img{
> remove, if it is no longer needed

done thanks

2024-01-03 14:13 UTC, PeterFreemann commented on lagcloud-website/src/component/Contactus.jsx
> +      <section classNameName="mb-4 services-section container-fluid mt-4 ">
> classNameName shouild be className

done thanks

2024-01-03 14:13 UTC, PeterFreemann commented on lagcloud-website/src/page/Home.jsx
> +import { Link } from "react-router-dom/cjs/react-router-dom.min";
> This should be `import { Link } from "react-router-dom";`

done thanks

2024-01-03 14:14 UTC, PeterFreemann commented
> in firebase.json file
> 
> remove what is there and add rhe following code:
> 
> ```
> {
>   "hosting": {
>     "public": "public/build",
>     "ignore": [
>       "firebase.json",
>       "**/.*",
>       "**/node_modules/**"
>     ],
>     "rewrites": [
>       {
>         "source": "**",
>         "destination": "/index.html"
>       }
>     ]
>   }
> }
> ```
> 
> Save and push

done thanks

2024-01-03 15:46 UTC, kobomarun requested changes

2024-01-03 15:46 UTC, kobomarun commented on lagcloud-website/src/component/Contactus.jsx
> +        <form action="your-server-action" method="POST">
remove this  <form className='mt-4' action="your-server-action " method="POST">
replace it with
<form className='mt-4' action="https://hooks.zapier.com/hooks/catch/17334671/3a8x32g/ " method="POST" target="_blank">

2024-01-08 13:52 UTC, PeterFreemann commented on lagcloud-website/public/assets/css/main.css
> +  padding: 0 140px;
> did you test this on mobile?

yes i did

2024-01-08 13:53 UTC, PeterFreemann commented on lagcloud-website/src/component/Contactus.jsx
> +                      <input type="email" className="form-control" id="Number" name="Number" required/>
> This should be `type=number `

done thanks

2024-01-08 13:54 UTC, PeterFreemann commented
> you didnt replace the <form i asked you to do

sorry pls which form @kobomarun

2024-01-08 20:20 UTC, kobomarun approved these changes

2024-01-08 20:46 UTC, merged